export const ADD_HIGHLIGHT = 'ADD_HIGHLIGHT'
export const COPY_DOCUMENT = 'COPY_DOCUMENT'
export const FILTER_HIGHLIGHTS = 'FILTER_HIGHLIGHTS'
export const TOGGLE_FILTER_HIGHLIGHT = 'TOGGLE_FILTER_HIGHLIGHT'
